if: tag IS present

matrix:
    include:
      - os: osx
        osx_image: xcode11.3
        language: node_js
        node_js: "12"
        env:
          - ELECTRON_CACHE=$HOME/.cache/electron
          - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
      - os: linux
        language: node_js
        node_js: "12"
  
cache:
  directories:
    - $HOME/.cache/yarn
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - yarn release

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

notifications:
  email: false