matrix:
    include:
      - os: osx
        osx_image: xcode11.3
        language: node_js
        node_js: "12"
        env:
          - ELECTRON_CACHE=$HOME/.cache/electron
          - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
      - os: linux
        language: node_js
        node_js: "12"
  
cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script: yarn test

deploy:
  provider: script
  script: bash deploy.travis.sh
  on:
    brach: master

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

notifications:
  email: false