matrix:
    include:
      - os: osx
        osx_image: xcode11.3
        language: node_js
        node_js: "12"
        env:
          - ELECTRON_CACHE=$HOME/.cache/electron
          - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
      - os: linux
        language: node_js
        node_js: "12"
  
cache:
  directories:
    - $HOME/.cache/yarn
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script: yarn build

deploy:
  provider: script
  script: yarn release
  on:
    tags: true

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

notifications:
  email: false